samples: [
    'Collibri_standard_protocol-HBR-Collibri-100_ng-2_S1_L001',
    'Collibri_standard_protocol-HBR-Collibri-100_ng-3_S2_L001',
    'Collibri_standard_protocol-UHRR-Collibri-100_ng-2_S3_L001',
    'Collibri_standard_protocol-UHRR-Collibri-100_ng-3_S4_L001',
    'KAPA_mRNA_HyperPrep_-HBR-KAPA-100_ng_total_RNA-2_S5_L001',
    'KAPA_mRNA_HyperPrep_-HBR-KAPA-100_ng_total_RNA-3_S6_L001',
    'KAPA_mRNA_HyperPrep_-UHRR-KAPA-100_ng_total_RNA-2_S7_L001',
    'KAPA_mRNA_HyperPrep_-UHRR-KAPA-100_ng_total_RNA-3_S8_L001'
    ]

out_fastqc: 'out/fastqc/'
out_multiqc: 'out/multiqc/'
out_fastqc_trimmed: 'out/fastqc_trimmed/'
out_multiqc_trimmed: 'out/multiqc_trimmed/'

data: 'data/'
data_trimmed: 'data_trimmed/'

reads:
  ['1', '2']
